env:
  contexts:
  - name: Atlantis_Authentication
    urls:
    - https://atlantis.greatwave.ai
    includePaths:
    - https://atlantis.greatwave.ai.*
    authentication:
      method: autodetect
      verification:
        method: autodetect
        loggedInRegex: \Qtest-user1\E
        pollFrequency: 60
        pollUnits: requests
        pollUrl: https://atlantis.greatwave.ai/agenteco?/loadDefaults
        pollPostData: ""
        pollAdditionalHeaders:
        - header: content-type
          value: application/x-www-form-urlencoded
    sessionManagement:
      method: autodetect
    technology: {}
    structure: {}
    users:
    - name: test-user1
      credentials:
        password: Test@1234
        username: test-user1
  parameters: {}
jobs:
- type: activeScan
  parameters:
    context: Atlantis_Authentication
    user: test-user1
    policy: ""
    maxRuleDurationInMins: 30
    maxScanDurationInMins: 30
    maxAlertsPerRule: 10
  policyDefinition:
    defaultStrength: medium
    defaultThreshold: medium

