name: Check run

on: [push]

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # Ensure this matches the branch where your file is located

   
    # Pass the plan file to the ZAP scan step using a relative path
    - name: ZAP Scan
      uses: zaproxy/action-af@v0.1.0
      with:
        plan: 'atlantis_active_report.yaml'

    - name: Copy report to repository directory
      run: cp /zap/wrk/2024-11-14-ZAP-Report-atlantis.greatwave.ai.html .

    - name: Commit report to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add 2024-11-14-ZAP-Report-atlantis.greatwave.ai.html
        git commit -m "Add ZAP report"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

