name: Test File Creation and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_write:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Pull ZAP Docker Image
      - name: Pull ZAP Docker Image
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP TEST
        run: |
          # Create an empty report file before running the scan to avoid permission issues
          touch report.html
          
          # Run the ZAP Baseline scan
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://example.com -r report.html


      # Step 4: Upload Test Report to Azure Blob Storage
      - name: Upload Test Report to Azure
        run: |
          az storage blob upload --account-name atlantisdevstorage001 \
          --container-name ramdev001 \
          --name path/to/report/zap_test_report.html \
          --file zap_test_report.html \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }}
