name: Test File Creation and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_write:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Pull ZAP Docker Image
      - name: Pull ZAP Docker Image
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      # Step 3: Run ZAP Full Scan
      - name: Run ZAP Full Scan
        run: |
          docker run \
            --network="host" \
            -v $(pwd):/zap/wrk/:rw -t ubuntu:20.04 touch /zap/wrk/test.txt
            ghcr.io/zaproxy/zaproxy:stable \
            sh -c "zap-full-scan.py -t https://example.com -r /zap/wrk/zap_report.html && chmod 666 /zap/wrk/zap_report.html"


      # Step 4: Upload Test Report to Azure Blob Storage
      - name: Upload Test Report to Azure
        run: |
          az storage blob upload --account-name atlantisdevstorage001 \
          --container-name ramdev001 \
          --name path/to/report/zap_test_report.html \
          --file zap_test_report.html \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }}
