name: ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

   
     # Pass the environment variables to the ZAP Docker container

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the ZAP scan using the Automation Framework
      - name: ZAP Scan
        uses: zaproxy/action-af@v0.1.0
      
      # Optional: Upload the ZAP report as an artifact
      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /zap/wrk/zap_report.html
