name: Check run

on: [push]

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # Ensure this matches the branch where your file is located

    - name: List files for debugging
      run: ls -R .github/workflows

        

    - name: Create a directory in the current workspace
      run: mkdir -p $GITHUB_WORKSPACE/zap
  
    - name: Copy ZAP plan file to the workspace directory
      run: cp .github/workflows/atlantis_plan.yaml $GITHUB_WORKSPACE/zap/plan.yml
  
    # Pass the plan file to the ZAP scan step using a relative path
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: 'https://www.example.com/'
        cmd_options: '-n $GITHUB_WORKSPACE/zap/plan.yml'



