name: Check run

on: [push]

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
     # Copy the plan file to the container's working directory
    - name: Copy ZAP plan file
      run: cp .github/workflows/atlantis_plan.yml /zap/wrk/plan.yml
      
    - name: ZAP Scan
      uses: zaproxy/action-af@v0.1.0
      with:
        plan: '/zap/wrk/plan.yml'


